Project: BucStop
_____________________________________________________________________

Description
_____________________________________________________________________
One paragraph og project description goes here.

Prerequisites
_____________________________________________________________________
Anything Required to run website/install

Installation
_____________________________________________________________________
How to install if applicable 

Citation
_____________________________________________________________________
Add any citations as needed
